name: 'autoencoder_kl'

in_channels: 3
out_channels: 3
latent_channels: 4
double_z: True
base_channels: 128
channel_multipliers: [1,2]
attention_resolutions: []
num_res_blocks: 2
dropout: 0.0
kl_weight: 1.0e-6
lpips_weight: 1.0