name: 'ddpm_unet_base'

backbone:
  in_channels: 1
  out_channels: 1
  base_channels: 32
  channel_multipliers: [1,2,4]
  time_emb_dim: 128
  

schedule:
  T: 1000
  beta_start: 0.0001
  beta_end: 0.02