name: 'ddpm_unet_attention'

backbone:
  in_channels: 3
  out_channels: 3
  base_channels: 32
  channel_multipliers: [1,2,4]
  attention_resolutions: [16]
  time_emb_dim: 128
  num_res_blocks: 2

schedule:
  T: 1000
  beta_start: 0.0001
  beta_end: 0.02